version: '3'
services:
  app:
    build: .
    command: bash -c 'npm start'
    image: line_bot_about_movie
    env_file: ./app.env
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    tty: true
